[world]
name = "starknet_battles"
description = "On-chain strategy game built with Dojo"
seed = "starknet_battles"

[env]
rpc_url = "http://localhost:5050"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[components]
# Game components will be defined here
